version: '3'


services:

  nginx:
    image: linder/custom-alpine-nginx:0.1
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
     - "8000:80"
    links:
     - sanic

  sanic:
    build: .
